<?php

		$SQL_PARROQUIA=mysql_query("SELECT * FROM parroquia WHERE id_parroquia='$IDENT_PARROQUIA'");
		$CP=mysql_num_rows($SQL_PARROQUIA);
		
			if($CP==0){
			$ID_PARROQUIA=0;
			$DESC_PARROQUIA="";
			
	$ID_CONDICIONPARROQUIA="";
	$DES_CONDICIONPARROQUIA="...";
				$BOTON="REGISTRAR";
			}else{
			$CAMPO_PARROQUIA=mysql_fetch_row($SQL_PARROQUIA);
			$ID_PARROQUIA=$CAMPO_PARROQUIA[0];
			$DESC_PARROQUIA=$CAMPO_PARROQUIA[1];
				$ID_CONDICIONPARROQUIA=$CAMPO_PARROQUIA[2];
				if($ID_CONDICIONPARROQUIA=="A"){
$DES_CONDICIONPARROQUIA="ACTIVO";
}else{
$DES_CONDICIONPARROQUIA="INACTIVO";
}
				
			$BOTON="MODIFICAR";
			}

?>
